-- Active: 1774368236280@@192.168.100.78@5436@dev_regulat
create schema if not exists cadoc_6334_v2;

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.conccred(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    brand integer NOT NULL,
    function varchar(1) NOT NULL,
    number_accredited_establishments bigint NOT NULL,
    number_active_establishments bigint NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_conccred_uk ON cadoc_6334_v2.conccred USING btree (year, quarter, brand, function);


-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.contatos(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    contact_type varchar(1) NOT NULL,
    name varchar(100) NOT NULL,
    position varchar(100),
    phone_number varchar(15) NOT NULL,
    email varchar(100) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_contatos_uk ON cadoc_6334_v2.contatos USING btree (year, quarter, contact_type, name);



-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.desconto(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year numeric NOT NULL,
    quarter numeric NOT NULL,
    function varchar(1) NOT NULL,
    brand numeric NOT NULL,
    capture_mode integer NOT NULL,
    installments integer NOT NULL,
    segment_code integer NOT NULL,
    avg_mdr_fee numeric(15,2) NOT NULL,
    min_mdr_fee numeric(15,2) NOT NULL,
    max_mdr_fee numeric(15,2) NOT NULL,
    stdev_mdr_fee numeric(15,2) NOT NULL,
    sqrdiff_mdr_fee numeric(15,2) NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_desconto_uk ON cadoc_6334_v2.desconto USING btree (year, quarter, function, brand, capture_mode, installments, segment_code);

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.infresta(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    federation_unit varchar(2) NOT NULL,
    establishment_total_quantity bigint NOT NULL,
    establishment_manual_capture_quantity bigint NOT NULL,
    establishment_eletronic_capture_quantity bigint NOT NULL,
    establishment_remote_capture_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_infresta_uk ON cadoc_6334_v2.infresta USING btree (year, quarter, federation_unit);

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.infrterm(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    federation_unit varchar(2) NOT NULL,
    pos_total_quantity bigint NOT NULL,
    pos_shared_quantity bigint NOT NULL,
    pos_chip_quantity bigint NOT NULL,
    pdv_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_infrterm_uk ON cadoc_6334_v2.infrterm USING btree (year, quarter, federation_unit);

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.intercam(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    product_code integer NOT NULL,
    card_type varchar(1) NOT NULL,
    function varchar(1) NOT NULL,
    brand integer NOT NULL,
    capture_mode integer NOT NULL,
    installments integer NOT NULL,
    segment_code integer NOT NULL,
    interchange_fee numeric(15,2) NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_intercam_uk ON cadoc_6334_v2.intercam USING btree (year, quarter, product_code, card_type, function, brand, capture_mode, installments, segment_code);


-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.luccred(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    gross_revenue numeric(15,2) NOT NULL,
    rental_revenue numeric(15,2) NOT NULL,
    others_revenue numeric(15,2) NOT NULL,
    interchange_cost numeric(15,2) NOT NULL,
    marketing_cost numeric(15,2) NOT NULL,
    brand_access_cost numeric(15,2) NOT NULL,
    risk_cost numeric(15,2) NOT NULL,
    processing_cost numeric(15,2) NOT NULL,
    others_cost numeric(15,2) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_luccred_uk ON cadoc_6334_v2.luccred USING btree (year, quarter);

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.ranking(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    establishment_code bigint NOT NULL,
    function character(1) NOT NULL,
    brand integer NOT NULL,
    capture_mode integer NOT NULL,
    installments integer NOT NULL,
    segment_code integer NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    avg_mcc_fee numeric(15,2) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_ranking_uk ON cadoc_6334_v2.ranking USING btree (year, quarter, establishment_code, function, brand, capture_mode, installments, segment_code);

drop table  cadoc_6334_v2.tmp_ranking_filtered;

-- Generated by the database client.
CREATE TABLE  cadoc_6334_v2.ranking_filtered(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    establishment_code bigint NOT NULL,
    function character(1) NOT NULL,
    brand integer NOT NULL,
    capture_mode integer NOT NULL,
    installments integer NOT NULL,
    segment_code integer NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    avg_mcc_fee numeric(15,2) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v2_ranking_filtered_uk ON cadoc_6334_v2.ranking_filtered USING btree (year, quarter, establishment_code, function, brand, capture_mode, installments, segment_code);


drop table if exists cadoc_6334_v2.segmento;

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v2.segmento(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    segment_name varchar(100) NOT NULL,
    segment_description varchar(250) NOT NULL,
    segment_code integer NOT NULL,
    PRIMARY KEY(id)
);

drop index if exists cadoc_6334_v2.cadoc_6334_v2_segmento_uk;

CREATE UNIQUE INDEX cadoc_6334_v2_segmento_uk ON cadoc_6334_v2.segmento USING btree (year, quarter, segment_code);