-- Active: 1766518799113@@127.0.0.1@5434@reg
create schema if not exists cadoc_6334_v3;

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.conccred(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    brand integer NOT NULL,
    function varchar(1) NOT NULL,
    number_accredited_establishments bigint NOT NULL,
    number_active_establishments bigint NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_conccred_uk ON cadoc_6334_v3.conccred USING btree (year, quarter, brand, function);


-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.contatos(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    contact_type varchar(1) NOT NULL,
    name varchar(100) NOT NULL,
    position varchar(100),
    phone_number varchar(15) NOT NULL,
    email varchar(100) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_contatos_uk ON cadoc_6334_v3.contatos USING btree (year, quarter, contact_type, name);



-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.desconto(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year numeric NOT NULL,
    quarter numeric NOT NULL,
    function varchar(1) NOT NULL,
    brand numeric NOT NULL,
    capture_mode integer NOT NULL,
    installments integer NOT NULL,
    segment_code integer NOT NULL,
    avg_mdr_fee numeric(15,2) NOT NULL,
    min_mdr_fee numeric(15,2) NOT NULL,
    max_mdr_fee numeric(15,2) NOT NULL,
    stdev_mdr_fee numeric(15,2) NOT NULL,
    sqrdiff_mdr_fee numeric(15,2) NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_desconto_uk ON cadoc_6334_v3.desconto USING btree (year, quarter, function, brand, capture_mode, installments, segment_code);

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.infresta(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    federation_unit varchar(2) NOT NULL,
    establishment_total_quantity bigint NOT NULL,
    establishment_manual_capture_quantity bigint NOT NULL,
    establishment_eletronic_capture_quantity bigint NOT NULL,
    establishment_remote_capture_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_infresta_uk ON cadoc_6334_v3.infresta USING btree (year, quarter, federation_unit);

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.infrterm(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    federation_unit varchar(2) NOT NULL,
    pos_total_quantity bigint NOT NULL,
    pos_shared_quantity bigint NOT NULL,
    pos_chip_quantity bigint NOT NULL,
    pdv_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_infrterm_uk ON cadoc_6334_v3.infrterm USING btree (year, quarter, federation_unit);

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.intercam(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    product_code integer NOT NULL,
    card_type varchar(1) NOT NULL,
    function varchar(1) NOT NULL,
    brand integer NOT NULL,
    capture_mode integer NOT NULL,
    installments integer NOT NULL,
    segment_code integer NOT NULL,
    interchange_fee numeric(15,2) NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_intercam_uk ON cadoc_6334_v3.intercam USING btree (year, quarter, product_code, card_type, function, brand, capture_mode, installments, segment_code);


-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.luccred(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    gross_revenue numeric(15,2) NOT NULL,
    rental_revenue numeric(15,2) NOT NULL,
    others_revenue numeric(15,2) NOT NULL,
    interchange_cost numeric(15,2) NOT NULL,
    marketing_cost numeric(15,2) NOT NULL,
    brand_access_cost numeric(15,2) NOT NULL,
    risk_cost numeric(15,2) NOT NULL,
    processing_cost numeric(15,2) NOT NULL,
    others_cost numeric(15,2) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_luccred_uk ON cadoc_6334_v3.luccred USING btree (year, quarter);

-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.ranking(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    establishment_code bigint NOT NULL,
    function character(1) NOT NULL,
    brand integer NOT NULL,
    capture_mode integer NOT NULL,
    installments integer NOT NULL,
    segment_code integer NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    avg_mcc_fee numeric(15,2) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_ranking_uk ON cadoc_6334_v3.ranking USING btree (year, quarter, establishment_code, function, brand, capture_mode, installments, segment_code);


-- Generated by the database client.
CREATE TABLE  cadoc_6334_v3.ranking_filtered(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    establishment_code bigint NOT NULL,
    function character(1) NOT NULL,
    brand integer NOT NULL,
    capture_mode integer NOT NULL,
    installments integer NOT NULL,
    segment_code integer NOT NULL,
    transaction_amount numeric(15,2) NOT NULL,
    transaction_quantity bigint NOT NULL,
    avg_mcc_fee numeric(15,2) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX cadoc_6334_v3_ranking_filtered_uk ON cadoc_6334_v3.ranking_filtered USING btree (year, quarter, establishment_code, function, brand, capture_mode, installments, segment_code);



-- Generated by the database client.
CREATE TABLE if not exists cadoc_6334_v3.segmento(
    id BIGSERIAL NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    segment_name varchar(100) NOT NULL,
    segment_description varchar(250) NOT NULL,
    segment_code integer NOT NULL,
    PRIMARY KEY(id)
);


CREATE UNIQUE INDEX cadoc_6334_v3_segmento_uk ON cadoc_6334_v3.segmento USING btree (year, quarter, segment_code);