SET search_path TO bins;

CREATE TABLE IF NOT EXISTS bins.master_ip0072t1 (
    "effective" CHAR(7) NOT NULL,
    "active" CHAR(1) NOT NULL,
    "member_id" CHAR(11) NOT NULL,
    "filler_1" CHAR(2) NOT NULL,
    "interchange_region" CHAR(1) NOT NULL,
    "iei_qualifier" CHAR(2) NOT NULL,
    "internal_member_id_ind" CHAR(1) NOT NULL,
    "acquirer_switch" CHAR(1) NOT NULL,
    "atm_ind" CHAR(1) NOT NULL,
    "rcl_region" CHAR(1) NOT NULL,
    "endpoint" CHAR(7) NOT NULL,
    "world_member_id_cbk_switch" CHAR(1) NOT NULL,
    "world_card_acc_mcc_group_cd1" CHAR(1) NOT NULL,
    "world_card_acc_mcc_group_cd2" CHAR(1) NOT NULL,
    "world_card_acc_mcc_group_cd3" CHAR(1) NOT NULL,
    "world_card_acc_mcc_group_cd4" CHAR(1) NOT NULL,
    "world_card_acc_mcc_group_cd5" CHAR(1) NOT NULL,
    "filler_2" CHAR(1) NOT NULL,
    "member_name" VARCHAR(64) NOT NULL,
    "country_code" CHAR(3) NOT NULL,
    "country_code_iso" CHAR(3) NOT NULL,
    "filler_3" CHAR(22) NOT NULL,
    "outbound_format_ind" CHAR(1) NOT NULL,
    "mc_electronic_card_ind" CHAR(1) NOT NULL,
    "eea_acquirer_country_service_ica" CHAR(1) NOT NULL,
    "filler_4" CHAR(1) NOT NULL,
    "national_payment_gateway_processor_switch" CHAR(1) NOT NULL,
    "payment_transfer_activity_particip_ind" CHAR(1) NOT NULL
);