SET search_path TO bins;

update bins
    set
       produto_intermediario = 
    CASE produto_base
        WHEN 'A' THEN 'Visa Traditional'
        WHEN 'B' THEN 'Visa Traditional Rewards'
        WHEN 'C' THEN 'Visa Signature'
        WHEN 'D' THEN 'Visa Signature Preferred'
        WHEN 'E' THEN 'Proprietary ATM'
        WHEN 'F' THEN 'Visa Classic'
        WHEN 'F2' THEN 'Visa Installment Credential'
        WHEN 'F3' THEN 'Visa Installment Credential Standard'
        WHEN 'G' THEN 'Visa Business'
        WHEN 'G1' THEN 'Visa Signature Business'
        WHEN 'G3' THEN 'Visa Business Enhanced/Visa Platinum Business'
        WHEN 'G4' THEN 'Visa Infinite Business'
        WHEN 'G5' THEN 'Visa Business Rewards'
        WHEN 'I' THEN 'Visa Infinite'
        WHEN 'I1' THEN 'Visa Infinite Privilege'
        WHEN 'I2' THEN 'Ultra High Net Worth'
        WHEN 'J3' THEN 'Visa Healthcare/Visa Workplace Benefits'
        WHEN 'K' THEN 'Visa Corporate T&E'
        WHEN 'K1' THEN 'Visa Government Corporate T&E'
        WHEN 'L' THEN 'Electron'
        WHEN 'M' THEN 'Visa Debit'
        WHEN 'M1' THEN 'Visa Debit Rewards'
        WHEN 'M2' THEN 'Visa Debit Platinum'
        WHEN 'M3' THEN 'Visa Debit Business'
        WHEN 'M4' THEN 'Visa Debit Business Platinum'
        WHEN 'M5' THEN 'Visa Debit Business Rewards'
        WHEN 'N0' THEN 'Visa Gold'
        WHEN 'N' THEN 'Visa Platinum'
        WHEN 'N1' THEN 'Visa Rewards'
        WHEN 'N2' THEN 'Visa Select'
        WHEN 'P' THEN 'Visa Gold'
        WHEN 'Q' THEN 'Private Label'
        WHEN 'Q2' THEN 'Private Label Basic'
        WHEN 'Q3' THEN 'Private Label Standard'
        WHEN 'Q4' THEN 'Private Label Enhanced'
        WHEN 'Q5' THEN 'Private Label Specialized'
        WHEN 'Q6' THEN 'Private Label Premium'
        WHEN 'R' THEN 'Proprietary'
        WHEN 'S' THEN 'Visa Purchasing'
        WHEN 'S1' THEN 'Visa Purchasing with Fleet'
        WHEN 'S2' THEN 'Visa Government Purchasing'
        WHEN 'S3' THEN 'Visa Government Purchasing with Fleet'
        WHEN 'S4' THEN 'Commercial Agriculture'
        WHEN 'S5' THEN 'Commercial Transport'
        WHEN 'S6' THEN 'Commercial Marketplace'
        WHEN 'U' THEN 'Visa TravelMoney'
        WHEN 'V' THEN 'V PAY'
        WHEN 'W^' THEN 'Visa Direct Payouts W'
        WHEN 'W1' THEN 'Visa Direct Payouts A'
        WHEN 'X' THEN 'Visa Commercial Choice Travel'
        WHEN 'X1' THEN 'Visa Commercial Choice Omni'
        ELSE 'Desconhecido'
END
  where bandeira = 'VISA';