INSERT INTO final_products (card_name, card_classification_code, card_classification_name) VALUES
-- Basico Nacional - codigo: 31
('MASTERCARD STANDARD CARD', 31, 'Basico Nacional'),
('ELO Básico', 31, 'Basico Nacional'),
('Electron', 31, 'Basico Nacional'),
('Pré Pago Uso Geral', 31, 'Basico Nacional'),
('ELO Básico com Conta de Pagamentos PF', 31, 'Basico Nacional'),
('Visa Debit Rewards', 31, 'Basico Nacional'),
('MASTERCARD DEBIT CARD', 31, 'Basico Nacional'),
('MASTERCARD DEBIT IMMEDIATE DEBIT', 31, 'Basico Nacional'),
('MASTERCARD DEBIT BUSINESSCARD CARD', 31, 'Basico Nacional'),
('MASTERCARD DEBIT UNEMBOSSED', 31, 'Basico Nacional'),
('MASTERCARD PREPAID DEBIT STANDARD-NON RELOADABLE', 31, 'Basico Nacional'),
('MASTERCARD PREPAID DEBIT STUDENT CARD', 31, 'Basico Nacional'),
('MASTERCARD PREPAID DEBIT UNEMBOSSED (NON-US)', 31, 'Basico Nacional'),
('DEBIT MASTERCARD CARD', 31, 'Basico Nacional'),
('Visa Traditional', 31, 'Basico Nacional'),
('Visa Traditional Rewards', 31, 'Basico Nacional'),
('Visa Rewards', 31, 'Basico Nacional'),
('DEBIT OTHER EMBOSSED', 31, 'Basico Nacional'),
('DEBIT MASTERCARD UNEMBOSSED', 31, 'Basico Nacional'),
('MASTERCARD STANDARD CARD-IMMEDIATE DEBIT', 31, 'Basico Nacional'),
('DEBIT OTHER 2 EMBOSSED', 31, 'Basico Nacional'),
('MASTERCARD UNEMBOSSED PREPAID STUDENT CARD', 31, 'Basico Nacional'),
('PREPAID MASTERCARD UNEMBOSSED (NON-US)', 31, 'Basico Nacional'),
-- Basico Internacional - codigo: 32
('Visa Classic', 32, 'Basico Internacional'),
('Visa Debit', 32, 'Basico Internacional'),
('MASTERCARD PREPAID DEBIT TRAVEL CARD', 32, 'Basico Internacional'),
('MASTERCARD STANDARD PREPAID', 32, 'Basico Internacional'),
('MASTERCARD CREDIT MIXED BIN CARD', 32, 'Basico Internacional'),
('MASTERCARD PREPAID DEBIT GIFT CARD', 32, 'Basico Internacional'),
('MASTERCARD PREPAID DEBIT STANDARD-RELOADABLE', 32, 'Basico Internacional'),
('ELO Mais', 32, 'Basico Internacional'),
('ELO Mais com conta de Pagamento PF', 32, 'Basico Internacional'),
('PREPAID MAESTRO OTHER CARD', 32, 'Basico Internacional'),
('Private Label Basic', 32, 'Basico Internacional'),
-- Intermediario - codigo: 33
('Visa Gold', 33, 'Intermediario'),
('MASTERCARD GOLD CARD', 33, 'Intermediario'),
('ELO Grafite', 33, 'Intermediario'),
('ELO Grafite com Conta de Pagamento PF', 33, 'Intermediario'),
('DEBIT GOLD MASTERCARD CARD', 33, 'Intermediario'),
('Elo Benefícios Flexíveis', 33, 'Intermediario'),
('Elo Benefícios Flex Pós', 33, 'Intermediario'),
('Elo Voucher com Elo Benefícios Flexívei', 33, 'Intermediario'),
-- Platinum - codigo: 34
('Visa Platinum', 34, 'Platinum'),
('MASTERCARD PLATINUM PREPAID TRAVEL CARD', 34, 'Platinum'),
('PLATINIUM MASTERCARD CARD', 34, 'Platinum'),
('PLATINUM MASTERCARD IMMEDIATE DEBIT', 34, 'Platinum'),
('DEBIT PLATINUM CARD', 34, 'Platinum'),
('Visa Debit Platinum', 34, 'Platinum'),
-- Premium - codigo: 35
('Visa Infinite', 35, 'Premium'),
('Visa Infinite Business', 35, 'Premium'),
('Visa Infinite Privilege', 35, 'Premium'),
('Visa Signature', 35, 'Premium'),
('Visa Signature Business', 35, 'Premium'),
('Visa Select', 35, 'Premium'),
('MASTERCARD BLACK', 35, 'Premium'),
('WORLD MASTERCARD CARD', 35, 'Premium'),
('MASTERCARD WORLD ELITE', 35, 'Premium'),
('WORLD ELITE MASTERCARD', 35, 'Premium'),
('WORLD ELITE DEBIT MASTERCARD / MASTERCARD BLACK DEBIT', 35, 'Premium'),
('WORLD SIGNIA MASTERCARD CARD-IMMEDIATE DEBIT', 35, 'Premium'),
('MASTERCARD NEW WORLD', 35, 'Premium'),
('MASTERCARD NEW WORLD-IMMEDIATE DEBIT', 35, 'Premium'),
('TITANIUM MASTERCARD CARD', 35, 'Premium'),
('LD MASTERCARD CARD-IMMEDIATE DEBIT', 35, 'Premium'),
('ELO Nanquim', 35, 'Premium'),
('ELO Diners Club', 35, 'Premium'),
('ELO Nanquim com Conta de Pagamento PF', 35, 'Premium'),
('TITANIUM DEBIT MASTERCARD', 35, 'Premium'),
-- Corporativo - codigo: 36
('Visa Corporate T&E', 36, 'Corporativo'),
('Visa Government Corporate T&E', 36, 'Corporativo'),
('Visa Commercial Choice Travel', 36, 'Corporativo'),
('MASTERCARD CORPORATE CARD', 36, 'Corporativo'),
('MASTERCARD CORPORATE IMMEDIATE DEBIT', 36, 'Corporativo'),
('MASTERCARD CORPORATE EXECUTIVE CARD', 36, 'Corporativo'),
('MASTERCARD EXECUTIVE BUSINESS CARD', 36, 'Corporativo'),
('MASTERCARD PURCHASING CARD', 36, 'Corporativo'),
('MASTERCARD FLEET CARD', 36, 'Corporativo'),
('MASTERCARD BUSINESS CARD PREPAID', 36, 'Corporativo'),
('MASTERCARD BUSINESS DEBIT', 36, 'Corporativo'),
('MASTERCARD BUSINESS CARD-IMMEDIATE DEBIT', 36, 'Corporativo'),
('MASTERCARD BUSINESS CARD', 36, 'Corporativo'),
('MASTERCARD BUSINESSCARD CARD', 36, 'Corporativo'),
('MASTERCARD PREPAID BUSINESS PREFERRED', 36, 'Corporativo'),
('MASTERCARD PREPAID DEBIT STANDARD-CONSUMER INCENTIVE', 36, 'Corporativo'),
('WORLD MASTERCARD FOR BUSINESS', 36, 'Corporativo'),
('Commercial Transport', 36, 'Corporativo'),
('Commercial Marketplace', 36, 'Corporativo'),
('Despesas Corporativas', 36, 'Corporativo'),
('Visa Healthcare/Visa Workplace Benefits', 36, 'Corporativo'),
('DEBIT MASTERCARD BUSINESSCARD CARD', 36, 'Corporativo'),
('Visa Debit Business', 36, 'Corporativo'),
('Visa Debit Business Platinum', 36, 'Corporativo'),
('Visa Debit Business Rewards', 36, 'Corporativo'),
('Visa Business Enhanced/Visa Platinum Business', 36, 'Corporativo'),
('Visa Business', 36, 'Corporativo'),
('BUSINESS PREMIUM DEBIT', 36, 'Corporativo'),
('PREFERRED BUSINESS CARD', 36, 'Corporativo'),
('Visa Business Rewards', 36, 'Corporativo'),
('MAESTRO SMALL BUSINESS CARD', 36, 'Corporativo'),
('MASTERCARD PREPAID DEBIT STANDARD-GOVERNMENT', 36, 'Corporativo'),
-- Empresarial - codigo: 37
('Corporativo', 37, 'Empresarial'),
('Empresarial Básico', 37, 'Empresarial'),
('Empresarial Grafite', 37, 'Empresarial'),
('Empresarial Mais', 37, 'Empresarial'),
('Empresarial Debito Internacional', 37, 'Empresarial'),
('Corporativo Nanquim Diners Club', 37, 'Empresarial'),
('Corporativo Diners Club', 37, 'Empresarial'),
('Conta de Pagamento PJ', 37, 'Empresarial'),
('Visa Purchasing with Fleet', 37, 'Empresarial'),
('Empresarial Mais com Conta de Pagto PJ', 37, 'Empresarial'),
-- Outros - Codigo: 38
('Proprietary ATM', 38, 'Outros'),
('Compras', 38, 'Outros'),
('Desconhecido', 38, 'Outros'),
('V PAY', 38, 'Outros'),
('MASTERCARD UNKNOWN PRODUCT', 38, 'Outros'),
('STANDARD DEFERRED', 38, 'Outros'),
('Elo Voucher e Benefícios Flex Pós', 38, 'Outros'),
('Visa Purchasing', 38, 'Outros');