truncate table final_modes;

INSERT INTO final_modes (codigo, instituicao) VALUES
('P', 'Banco Bradesco S.A.'),
('P', 'BANCO BRADESCO SA'),
('P', 'ITAU UNIBANCO S.A.'),
('P', 'BANCO BMG S/A'),
('P', 'NU PAGAMENTOS SA'),
('P', 'Itau Unibanco Holding S.A.'),
('P', 'Banco do Brasil S.A.'),
('P', 'Banco Santander S.A.'),
('P', 'Banco Cooperativo Sicredi S.A.'),
('P', 'BANCO VOTORANTIM S/A'),
('P', 'PICPAY BANK BANCO MULTIPLO S A'),
('P', 'BANCO C6 SA'),
('P', 'Banco Bradescard S.A.'),
('P', 'BANCO DO BRASIL, S.A.'),
('P', 'BANCO DO BRASIL SA'),
('P', 'BANCO AGIBANK S.A.'),
('P', 'BANCO PAN SA'),
('P', 'Banco BV S.A.'),
('P', 'BANCO INTER S.A.'),
('P', 'BANCO SANTANDER (BRASIL) S.A.'),
('P', 'Banco Digio S.A.'),
('P', 'Neon Pagamentos S.A.'),
('P', 'BANCO BRADESCARD S.A.'),
('P', 'Banco Mercantil do Brasil S.A.'),
('P', 'Fitbank Pagamentos Eletronicos SA'),
('P', 'Banco Digio Driver'),
('P', 'BANK OF AMERICA, NATIONAL ASSO'),
('P', 'Realize Credito Financiamento e Investimento S.A .'),
('P', 'REALIZE CREDITO FINANCIAMENTO'),
('P', 'BPCE'),
('P', 'Caixa Economica Federal'),
('P', 'BV Financeira SA Credito Financiamento e'),
('P', 'MIDWAY S.A. - CREDITO, FINANCI'),
('P', 'CREDIT AGRICOLE S.A.'),
('P', 'BANCO COOPERATIVO SICOOB S.A.'),
('P', 'PostFinance AG'),
('P', 'STARK BANK SA'),
('P', 'NIKY INSTITUICAO DE PAGAMENTO'),
('P', 'DM Financeira S.A. Credito Financiamento e Investimento'),
('P', 'La Banque Postale'),
('P', 'Banco Pan, S.A.'),
('P', 'SWAP MEIOS DE PAGAMENTOS SA'),
('P', 'BANCO DE BRASILIA S.A.'),
('P', 'BANCO CSF S/A'),
('P', 'BANCO COOPERATIVO SICREDI SA'),
('P', 'CAPITAL ONE, NATIONAL ASSOCIAT'),
('P', 'CAIXA ECONOMICA FEDERAL'),
('P', 'Banco CSF, S.A.'),
('P', 'BANCO DO ESTADO DO PARA S.A.'),
('P', 'Financeira Itau Cbd S.A. Credito Financiamento e Investimento'),
('P', 'PORTOSEG S.A. CREDITO FINANCIA'),
('P', 'Midway, S.A. - Credito Financiamento e Investimento'),
('P', 'REVOLUT LTD'),
('P', 'BRB-Banco de Brasilia S.A.'),
('P', 'ASAAS Gestao Financeira S A'),
('P', 'Societe Generale S.A.'),
('P', 'Banco Union S.A.'),
('P', 'N26 GMBH'),
('P', 'Revolut Bank UAB'),
('P', 'JPMorgan Chase Bank N.A.'),
('P', 'BANQUE FEDERATIVE DU CREDIT MU'),
('P', 'Dock Instituicao de Pagamento S.A.'),
('P', 'BNP Paribas'),
('P', 'Banco Cooperativo Sicoob S.A.'),
('P', 'BBC SA'),
('P', 'WILL FINANCEIRA S.A. CREDITO,'),
('P', 'Mercado Pago Instituicao de Pagamento Ltda.'),
('P', 'BANCO BRADESCO S.A.'),
('P', 'Capital One, National Association'),
('P', 'CITIBANK N.A.'),
('P', 'BANCO DAYCOVAL S.A.'),
('P', 'Wells Fargo Bank, National Association'),
('P', 'Credit Agricole Societe Anonyme'),
('P', 'BANCOLOMBIA S.A.'),
('P', 'BIZ INSTITUICAO DE PAGAMENTO LTDA'),
('P', 'BANCO DO ESTADO DO RIO GRANDE'),
('P', 'BANCO BTG PACTUAL SA'),
('P', 'Banco Safra S.A.'),
('P', 'Edenred Solucoes de Pagamento Hyla SA'),
('P', 'GOLDMAN SACHS BANK USA'),
('P', 'Wise Europe SA/NV'),
('P', 'Banque federative du credit mutuel'),
('P', 'BARCLAYS BANK UK PLC'),
('P', 'Caixabank S.A.'),
('P', 'JPMorgan Chase Bank N.A. - Debit'),
('P', 'Allied Irish Banks, p.l.c.'),
('P', 'BANCO TRIANGULO S/A'),
('P', 'PAGSEGURO INTERNET LTDA'),
('P', 'Realize Sociedade de Cr�dito Financiamento e Investimento S.A.'),
('P', 'CRED-SYSTEM ADMINISTRADORA DE'),
('P', 'MONZO BANK LIMITED'),
('P', 'BIZ INSTITUICAO DE PAGAMENTO S.A'),
('P', 'Bank of America - Consumer Credit'),
('P', 'Servired, Sociedad Espanola de Medios de Pago, S.A'),
('P', 'DEUTSCHER SPARKASSEN UND GIROV'),
('P', 'Lloyds Bank Plc'),
('P', 'The Toronto-Dominion Bank'),
('P', 'SISPRIME DO BRASIL COOPERATIVA'),
('P', 'Canadian Imperial Bank of Commerce'),
('P', 'CREDIT MUTUEL ARKEA'),
('P', 'BAWAG P.S.K. Bank fuer Arbeit und Wirtschaft und Osterreichische Postsparkasse A'),
('P', 'FORTBRASIL INSTITUIC?O DE PAGA'),
('P', 'Verde Administradora de Cartoes de Credi'),
('P', 'BULLLA S.A'),
('P', 'Banco de Bogota'),
('P', 'ZOOP TECNOLOGIA & INSTITUICAO DE PAGAMEN'),
('P', 'COMMONWEALTH BANK OF AUSTRALIA'),
('P', 'Banco do Nordeste do Brasil S.A.'),
('P', 'POSTEPAY S.P.A'),
('P', 'Banco Bilbao Vizcaya Argentaria Colombia S.A. "Bbva Colombia"'),
('P', 'BANCO FALABELLA'),
('P', 'Banco de Credito del Peru'),
('P', 'DZ BANK AG DEUTSCHE ZENTRAL-GE'),
('P', 'ING Bank'),
('P', 'BELFIUS BANK N.V. / BELFIUS BA'),
('P', 'BBVA Mexico S.A.'),
('P', 'Banco XP S.A.'),
('P', 'BANCO SANTANDER S.A.'),
('P', 'U.S. Bank National Association-Credit'),
('P', 'ACESSO SOLUCOES DE PAGAMENTO S'),
('P', 'Wise Payments Limited'),
('P', 'HSBC UK Bank plc'),
('P', 'UNICREDIT SPA'),
('P', 'CARUANA S.A. - SOCIEDADE DE CR'),
('P', 'Banco Davivienda S.A.'),
('P', 'Bancolombia S.A.'),
('P', 'REVOLUT LIMITED'),
('P', 'UBS Switzerland AG'),
('P', 'VISECA PAYMENT SERVICES SA'),
('P', 'Banco Triangulo S.A.'),
('P', 'Deutsche Kreditbank AG'),
('P', 'Confederacao Nacional das Cooperativas Centrais Unicred LTDA - Unicred do Brasil'),
('P', 'INTESA SANPAOLO SPA'),
('P', 'PSA PAYMENT SERVICES AUSTRIA G'),
('P', 'RendimentoPay Instituicao de Pagamento S.A.'),
('P', 'BANCO INVESTCRED UNIBANCO S A'),
('P', 'ING BANK N.V.'),
('P', 'Banco Pan Sa'),
('P', 'BANQI INSTITUICAO DE PAGAMENTO'),
('P', 'WELLS FARGO BANK, N.A.'),
('P', 'ECONSTAR SA'),
('P', 'BNP PARIBAS FORTIS NV/SA.'),
('P', 'BARCLAYS BANK DELAWARE'),
('P', 'Banco Comercial Portugues S.A.'),
('P', 'SANTANDER UK PLC'),
('P', 'NATIONAL WESTMINSTER BANK PLC'),
('P', 'Banco Mercantil Santa Cruz, S.A.'),
('P', 'SIX BBS AG'),
('P', 'Wise Brasil Pagamentos Ltda.'),
('P', 'Firstrand Bank Limited'),
('P', 'RECARGAPAY INSTITUICAO DE PAGA'),
('P', 'Banco de Chile'),
('P', 'DZ Bank AG'),
('P', 'Banco do Estado do Rio Grande do Sul S/A'),
('P', 'Banco Popular de Puerto Rico'),
('P', 'SEB KORT BANK AB'),
('P', 'CAPITEC BANK LIMITED'),
('P', 'Citibank, N.A.- Costco'),
('P', 'DBS Bank Ltd'),
('P', 'DEUTSCHE KREDITBANK AKTIENGESE'),
('P', 'Cooper Card Instituicao de Pagamento Ltda.'),
('P', 'Nordea Bank Abp'),
('P', 'Nationwide Building Society'),
('P', 'NEXI PAYMENTS SPA'),
('P', 'Interbank - Banco Internacional del Peru'),
('P', 'Banco de Occidente S.A.'),
('P', 'CAPITAL ONE BANK (CANADA BRANC'),
('P', 'HDFC Bank Limited'),
('P', 'NU MEXICO FINANCIERA S.A. DE C'),
('P', 'Bank of Scotland PLC'),
('P', 'ORBITALL SERVICOS E PROCESSAME'),
('P', 'Banco BBVA  Peru'),
('P', 'ING-DiBa AG'),
('P', 'NORDEA BANK AB (PUBL)'),
('P', 'Brasil Card Instituicao de Pagamentos Ltda.'),
('P', 'Cuscal Limited'),
('P', 'BANCO SANTANDER TOTTA S.A.'),
('P', 'ISSUER ADMINISTRADORA DE CARTOES LTDA'),
('P', 'Viseca Payment Services SA'),
('P', 'CURVE UK LIMITED'),
('P', 'BANCO SANTANDER CHILE'),
('P', 'Le Credit Lyonnais'),
('P', 'FIRST BANK'),
('P', 'Ticket Serviços SA'),
('P', 'Sodexo Pass do Brasil Serviços de Inovaç'),
('P', 'Alelo'),
('P', 'Corner Banca S.A.'),
('P', 'Kina Securities Limited'),
('P', 'Alpian SA'),
('P', 'Compropago S.A. de C.V., I.F.P.E.'),
('P', 'VODAFONE FIJI PTE LIMITED'),
('P', 'MITSUBISHI UFJ NICOS CO., LTD.'),
('P', 'Agos Ducato S.P.A.'),
('P', 'BOKF, National Association'),
('P', 'New Wave Capital Limited'),
('P', 'Stripe Technology Europe Ltd.'),
('P', 'Banistmo, S.A.'),
('P', 'MBNA Limited'),
('P', 'Intesa Sanpaolo S.P.A.'),
('P', 'Mitsubishi UFJ Nicos Co., Ltd'),
('P', 'BSK 1818 AG'),
('P', 'Caixa Economica Montepio Geral'),
('P', 'Neat Limited'),
('P', 'BNP PARIBAS FORTIS'),
('P', 'BANCAR TECNOLOGIA CO SA COMPAN'),
('P', 'BUNQ B.V.'),
('P', 'Banque Laurentienne du Canada'),
('P', 'Caixa Economica de Cabo Verde'),
('P', 'Reap Technologies Limited'),
('P', 'Mora Banc Grup SA'),
('P', 'Aevis Europa S.L.'),
('P', 'TIDE PLATFORM LIMITED'),
('P', 'REPOM, S.A.'),
('P', 'DiPocket UAB'),
('P', 'NUMIA S.p.A.'),
('P', 'La Federation des Caisses Desjardins du Quebec'),
('P', 'POWSZECHNA KASA OSZEDNOSCI B'),
('P', 'Deutscher Sparkassen- und Giroverband'),
('P', 'NEWDAY LTD'),
('P', 'Wise Asia-Pacific Pte. Ltd.'),
('P', 'Banca Sella S.P.A.'),
('P', 'UBS SWITZERLAND AG'),
('P', 'SOCIETE GENERALE'),
('P', 'BNP PARIBAS'),
('P', 'AS LHV PANK'),
('P', 'Union Gabonaise de Banques'),
('P', 'CURRENSEA LTD'),
('P', 'CORNER BANCA S.A.'),
('P', 'MASTER RED EUROPA S.L.'),
('P', 'Raiffeisen Schweiz Genossenschaft'),
('P', 'WISE AUSTRALIA PTY. LTD.'),
('P', 'Wallester AS'),
('P', 'SOGEXIA SA'),
('P', 'HSBC MEXICO, S.A. INSTITUCION'),
('P', 'BANESCO, S.A.'),
('P', 'Wise Australia Pty Ltd'),
('P', 'SECURITY SERVICE FEDERAL CREDI'),
('P', 'Lydia Solutions SAS'),
('P', 'Central Africa Building Society (CABS)'),
('P', 'PEOPLES TRUST COMPANY'),
('P', 'YOU TECHNOLOGIES GROUP (SINGAP'),
('P', 'OCA S.A.'),
('P', 'EURO KARTENSYSTEME GMBH'),
('P', 'Peoples Trust Company'),
('P', 'Visa Belgium'),
('P', 'Visalux S.C.'),
('P', 'ALAU TECNOLOGIA S.A.U.'),
('P', 'Banesco USA'),
('P', 'ForisGFS UK Limited'),
('P', 'permanent tsb plc'),
('P', 'Alquimia Digital MX S.A.P.I. de C.V. (OFFBOARDING)'),
('P', 'NETWORK INTERNATIONAL LLC'),
('P', 'Caja de Ahorros'),
('P', 'Pathward, N.A.'),
('P', 'Cooperativa Nacional de Educadores R.L. (Coopenae R.L.)'),
('P', 'FINDOMESTIC BANCA SPA'),
('P', 'ROCKLAND TRUST COMPANY'),
('P', 'Commerce Bancshares, Inc.'),
('P', 'KNAB N.V.'),
('P', 'BANCA NAZIONALE DEL LAVORO S.P'),
('P', 'Caixa Geral de Depositos S.A.'),
('P', 'Contecnica S.A.'),
('P', 'Santander UK Plc'),
('P', 'JACK HENRY & ASSOCIATES'),
('P', 'Deblock SAS'),
('P', 'EQUALS MONEY INTERNATIONAL LIM'),
('P', 'MADISON CF UK LIMITED'),
('P', 'Solaris SE'),
('P', 'MYPOS LIMITED'),
('P', 'FORIS MT LTD'),
('P', 'Asociacion Cibao de Ahorros y Prestamos'),
('P', 'Banesco (Panama), S.A.'),
('P', 'EQUALS MONEY EUROPE SA'),
('P', 'ING Belgium SA/NV'),
('P', 'Citi Commercial'),
('P', 'BIBANCA S.P.A.'),
('P', 'CSU DIGITAL S.A.'),
('P', 'ITAU CORPBANCA COLOMBIA, S.A.'),
('P', 'J P MORGAN EUROPE LTD'),
('P', 'UENO HOLDING S.A.E.C.A.'),
('P', 'TARJETAS BANAMEX, SA DE CV, SO'),
('P', 'GETNET ADQUIRENCIA E SERVICOS PARA MEIOS'),
('P', 'Monavate Limited'),
('P', 'PREX CHILE SA'),
('P', 'FEDERATION DES CAISSES DESJARD'),
('P', 'FISERV SOLUTIONS, LLC'),
('P', 'EQUITY BANQUE COMMERCIALE DU CONGO SA (EQUITYBCDC)'),
('P', 'Nimbus LLC'),
('P', 'MERCADOLIBRE SA DE CV INSTITUC'),
('P', 'Banque Internationale Arabe de Tunisie'),
('P', 'CAR S.A.'),
('P', 'Airwallex Pty Ltd'),
('P', 'Okali'),
('P', 'UAB ZEN.COM'),
('P', 'ING BELGIUM'),
('P', 'FINDARIN SA'),
('P', 'FIRST RATE EXCHANGE SERVICES L'),
('P', 'BANISTMO S.A'),
('P', 'Tarjeta Naranja S.A.'),
('P', 'CAPITAL ONE (EUROPE) PLC'),
('P', 'Xfers Pte Ltd'),
('P', 'Norfina Limited'),
('P', 'Solventa Tarjetas S.A.'),
('P', 'DOLARAPP MEXICO SA DE CV'),
('P', 'CAT ADMINISTRADORA DE TARJETAS'),
('P', 'MONAVATE LIMITED'),
('P', 'MOORWAND LTD'),
('P', 'IMMERSVE LTD'),
('P', 'WESTPAC NEW ZEALAND LIMITED'),
('P', 'TRELLANCE, INC.'),
('P', 'Travel Wallet Co., Ltd.'),
('P', 'Companhia Global de Solucoes e Servicos'),
('P', 'VJA'),
('P', 'BNEXT ELECTRONIC ISSUER, E.D.E'),
('P', 'PSCU INCORPORATED'),
('P', 'Foreningen af Danske Kortudstedere F.M.B.A'),
('P', 'Eika Gruppen AS'),
('P', 'AREEBA S.A.L'),
('P', 'MASTERCAJAS S.A.'),
('P', 'TEYA ICELAND HF.'),
('P', 'Ticket Serviços SA'),
('P', 'Sodexo Pass do Brasil Serviços de Inovaç'),
('P', 'POWSZECHNA KASA OSZEDNOSCI B'),
('P', 'Alquimia Digital MX S.A.P.I. de C.V. (OFFBOARDING)'),
('P', 'Digicash do Brasil Ltda.'),
('P', 'TREEZOR SAS'),
('P', 'TENPO PREPAGO S.A.'),
('P', 'ADMINISTRADORA DE TARJETAS DE'),
('P', 'Sodexo Pass do Brasil Serviços de Inovaç'),
('P', 'Ticket Serviços SA'),
('P', 'Alquimia Digital MX S.A.P.I. de C.V. (OFFBOARDING)'),
('P', 'POWSZECHNA KASA OSZCZEDNOSCI B'),
('P', 'Banco Bradescard');
-- Instituições Comerciais - Codigo C
INSERT INTO final_modes (codigo, instituicao) VALUES
('C', 'Portoseg S.A. Credito Financiamento e Investimento'),
('C', 'Pagseguro Internet S.A'),
('C', 'Volus Tecnologia e Gestao de Beneficios'),
('C', 'EDENRED SOLUCOES DE PAGAMENTOS'),
('C', 'ACG INSTITUIC?O DE PAGAMENTO S'),
('C', 'CREFISA SA CREDITO FINANCIAMEN'),
('C', 'Voxcred Administradora de Cartoes Servic'),
('C', 'Alpha Serviços de Rede de Autoatendiment'),
('C', 'BTR Administradora de Cartao de Credito'),
('C', 'SEAC - Sergipe Administradora de Servico'),
('C', 'Pernambucanas Financiadora SA Cred Fin e'),
('C', 'ViaCajas S.A.'),
('C', 'BOKIS'),
('C', 'PROMOTORA CMR FALABELLA S.A.'),
('C', 'LUFTHANSA AIRPLUS SERVICEKARTE'),
('C', 'Luizacred S.A. Sociedade de Credito, Financiamento e Investimento');



