DROP TABLE IF EXISTS bins.master_bin_dual_message_system_mpe;
CREATE TABLE IF NOT EXISTS bins.master_bin_dual_message_system_mpe (
    id BIGINT NOT NULL,
    accountlevel_management_activation_date CHAR(6),
    accountlevel_management_participation_indicator CHAR(1),
    active CHAR(1),
    anonymous_prepaid_indicator CHAR(1),
    authentication_indicator CHAR(1),
    bin_range_high BIGINT,
    bin_range_low BIGINT,
    card_program_identifier VARCHAR(10),
    cardholder_billing_currency CHAR(28),
    cardholder_billing_currency_default CHAR(3),
    cardholder_billing_currency_exponent_default CHAR(1),
    cardholder_billing_primary_currency CHAR(3),
    cardholder_billing_primary_currency_exponent CHAR(1),
    cardholder_billing_primary_transaction_currency CHAR(3),
    cardholder_currency_indicator CHAR(1),
    cash_access_only_participating_indicator CHAR(1),
    cash_back_without_purchase_indicator CHAR(1),
    chipto_magnetic_conversion_service_indicator CHAR(1),
    co_brand_participation_switch CHAR(1),
    contactless_enabled_indicator CHAR(1),
    country_code_alpha CHAR(3),
    country_code_numeric CHAR(3),
    created_date TIMESTAMP,
    durbin_regulated_rate_indicator CHAR(1),
    effective CHAR(7),
    endpoint CHAR(7),
    faster_funds_indicator CHAR(1),
    first_presentment_reassignment_switch CHAR(1),
    floor_expiration_date CHAR(6),
    gcms_product_id CHAR(3),
    issuer_account_range_high VARCHAR(20),
    issuer_account_range_low VARCHAR(20),
    issuer_card_program_identifier_priority_code CHAR(2),
    issuer_target_market_participation_indicator CHAR(1),
    licensed_product_id CHAR(3),
    mapping_service_indicator CHAR(1),
    meal_voucher_indicator CHAR(1),
    member_id CHAR(11),
    merchant_cleansing_activation_date CHAR(6),
    merchant_cleansing_service_participation CHAR(1),
    money_send_indicator CHAR(1),
    non_reloadable_prepaid_switch VARCHAR(2),
    post_dateservice_indicator CHAR(1),
    product_class VARCHAR(10),
    product_reassignment_switch CHAR(1),
    product_type_id CHAR(1),
    psn_route_indicator CHAR(1),
    pwcb_opt_in_switch CHAR(1),
    re_power_reload_participation_indicator CHAR(1),
    region CHAR(1),
    regulated_rate_type_indicator CHAR(1),
    spend_control_switch CHAR(1),
    table_id CHAR(3),
    transaction_routingi_ndicator CHAR(1),
    updated_date TIMESTAMP
);

create index master_bin_dual_message_system_mpe_bin_range_low_high
    on bins.master_bin_dual_message_system_mpe (bin_range_low, bin_range_high);

DROP TABLE IF EXISTS bins.master_bin_single_message_system_fit;
CREATE TABLE IF NOT EXISTS bins.master_bin_single_message_system_fit (
    id BIGINT NOT NULL,
    anonymous_prepaid_indicator CHAR(1),
    atm_surcharge CHAR(1),
    bin_reference_number CHAR(4),
    cdc_flag CHAR(1),
    cirrus_flag CHAR(1),
    country_code CHAR(3),
    created_date TIMESTAMP,
    cvc3_onbehalf_services_indicator_flag CHAR(1),
    debit_mastercard_flag CHAR(1),
    deposit_participation_flag CHAR(1),
    effective_date CHAR(6),
    effective_type CHAR(1),
    filler CHAR(1),
    id_length CHAR(2),
    identifier VARCHAR(20),
    identifier_high BIGINT,
    identifier_low BIGINT,
    installment_flag CHAR(1),
    issuer_processor_id CHAR(4),
    local_use_only_flag CHAR(1),
    maestro_flag CHAR(1),
    maestro_pinless_program_indicator CHAR(1),
    mastercard_flag CHAR(1),
    message_type_indicator CHAR(4),
    mgip_flag CHAR(1),
    ms_atm CHAR(1),
    ms_intracurrency CHAR(6),
    ms_pos CHAR(1),
    parcelas_flag CHAR(1),
    pin_ecommerce_flag CHAR(1),
    pin_management_flag CHAR(1),
    plus_flag CHAR(1),
    positive_id_flag CHAR(1),
    post_dated_flag CHAR(1),
    preferred_routing_indicator_atm CHAR(1),
    preferred_routing_indicator_pos CHAR(1),
    primary_account_number CHAR(2),
    private_label_flag CHAR(1),
    region_code CHAR(2),
    stand_in_flag CHAR(1),
    state_code CHAR(2),
    token_indicator_flag CHAR(1),
    updated_date TIMESTAMP,
    visa_flag CHAR(1),
    maestro_product_code CHAR(3)
);

create index master_bin_single_message_system_fit_identifier_low_high
    on bins.master_bin_single_message_system_fit (identifier_low, identifier_high);